language: go

go:
  - 1.12

env:
  - GO111MODULE=on

script:
  - make build
  - make test
  - make run
  - make bench

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
